// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	kafka "github.com/confluentinc/confluent-kafka-go/v2/kafka"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// KafkaConsumer is an autogenerated mock type for the KafkaConsumer type
type KafkaConsumer struct {
	mock.Mock
}

// Close provides a mock function with no fields
func (_m *KafkaConsumer) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReadMessage provides a mock function with given fields: timeout
func (_m *KafkaConsumer) ReadMessage(timeout time.Duration) (*kafka.Message, error) {
	ret := _m.Called(timeout)

	if len(ret) == 0 {
		panic("no return value specified for ReadMessage")
	}

	var r0 *kafka.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(time.Duration) (*kafka.Message, error)); ok {
		return rf(timeout)
	}
	if rf, ok := ret.Get(0).(func(time.Duration) *kafka.Message); ok {
		r0 = rf(timeout)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*kafka.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(time.Duration) error); ok {
		r1 = rf(timeout)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Subscribe provides a mock function with given fields: topic, rebalanceCb
func (_m *KafkaConsumer) Subscribe(topic string, rebalanceCb kafka.RebalanceCb) error {
	ret := _m.Called(topic, rebalanceCb)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, kafka.RebalanceCb) error); ok {
		r0 = rf(topic, rebalanceCb)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewKafkaConsumer creates a new instance of KafkaConsumer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKafkaConsumer(t interface {
	mock.TestingT
	Cleanup(func())
}) *KafkaConsumer {
	mock := &KafkaConsumer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
